let myImage = img`
    ..............................
    ..............................
    ................88..88........
    ..........7.....88..88........
    ..8.8.....77..................
    .......777777.................
    .8...8....77..88......88......
    ..888.....7...88......88......
    ................888888........
    ................888888........
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    `
let picture = images.stretchImage(myImage, 1, 1)
images.blit(
picture,
0,
0,
image.getDimension(picture, image.Dimension.Width),
image.getDimension(picture, image.Dimension.Height),
scene.backgroundImage(),
20,
20,
image.getDimension(picture, image.Dimension.Width) * 5,
image.getDimension(picture, image.Dimension.Height) * 5
)
